BASE_URL = "https://djinni.co"
PYTHON_URL = BASE_URL + "/jobs/?primary_keyword=Python"
LOGIN_URL = "https://djinni.co/login?from=frontpage_main"

TECHNOLOGIES = [
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "AWS",
    "Azure",
    "Git",
    "SQL",
    "REST",
    "JavaScript",
    "HTML",
    "CSS",
    "React",
    "Vue.js",
    "Angular",
    "Celery",
    "Docker",
    "Kubernetes",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "GraphQL",
    "CI/CD",
    "Jenkins",
    "CircleCI",
    "pytest",
    "unittest",
    "WebSockets",
    "OAuth",
    "JSON Web Tokens",
    "JWT",
    "RabbitMQ",
    "Elasticsearch",
    "Caching strategies",
    "Beautiful Soup",
    "Scrapy",
    "scikit-learn",
    "TensorFlow",
    "PyTorch",
    "pandas",
    "NumPy",
    "JIRA",
    "GitHub",
    "GitLab",
    "Tornado",
    "Pyramid",
    "Flask-RESTful",
    "Flask-SQLAlchemy",
    "Flask-WTF",
    "Cassandra",
    "CouchDB",
    "ArangoDB",
    "DynamoDB",
    "InfluxDB",
    "Neo4j",
    "Ansible",
    "Terraform",
    "Chef",
    "Puppet",
    "OpenShift",
]
